name: Selftest

on:
  pull_request:
  workflow_dispatch:

jobs:
  setup-alire:
    name: setup (${{ matrix.target }}, ${{ matrix.os }}, msys2=${{ matrix.msys2 }}, ${{ matrix.toolchain.id }})
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-13          # x64
          - macos-latest      # arm64
          - ubuntu-latest     # x64
          - ubuntu-24.04-arm  # arm64
          - windows-latest
        target:
            - nightly
            - source
            - stable
        msys2:  [true, false]
        toolchain:
          # The two first ones should be equivalent, but just in case
          - args: 'gnat_native gprbuild'
            id: explicit toolchain
          - args: '--select'
            id: interactive toolchain
          - args: '--disable-assistant'
            id: no toolchain
        exclude:
          - os: macos-13
            msys2: true
          - os: macos-latest
            msys2: true
          - os: ubuntu-latest
            msys2: true

    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup stable
        if: matrix.target == 'stable'
        uses: ./ # This uses the action code in the current PR
        with:
          msys2: ${{ matrix.msys2 }}
          cache: false
          toolchain: ${{ matrix.toolchain.args }}
          # We test without cache, as caching is tested in a separate workflow.
          # This way we make sure the cache isn't hiding any issue.

      - name: Setup nightly
        if: matrix.target == 'nightly'
        uses: ./
        with:
          msys2: ${{ matrix.msys2 }}
          version: nightly
          toolchain: ${{ matrix.toolchain.args }}
          cache: false

      - name: Setup from source (master)
        if: matrix.target == 'source'
        uses: ./
        with:
          msys2: ${{ matrix.msys2 }}
          branch: master
          toolchain: ${{ matrix.toolchain.args }}
          cache: false

      # Check alr and default toolchains
      - run: alr -n version
      - run: |
          alr -n init --bin alrws
          cd alrws
          alr exec -- gnat --version
          alr exec -- gprbuild --version
        if: matrix.toolchain.args != '--disable-assistant'
        # alr init fails without a toolchain

      # Verify proper OS

      - run: alr -n version | grep "os:" | grep LINUX
        if: matrix.os == 'ubuntu-latest'
        shell: bash

      - run: alr -n version | grep "os:" | grep MACOS
        if: matrix.os == 'macos-latest'
        shell: bash

      - run: alr -n version | grep "os:" | grep WINDOWS
        if: matrix.os == 'windows-latest'
        shell: bash

      # Verify proper architecture

      - uses: mosteo-actions/alr-arch-checker@v1

      # Verify proper msys2 behavior

      - run: alr -n version | grep "distribution:" | grep MSYS2
        if: matrix.os == 'windows-latest' && matrix.msys2 == true
        shell: bash

      - run: alr -n version | grep "distribution:" | grep UNKNOWN
        if: matrix.os == 'windows-latest' && matrix.msys2 == false
        shell: bash
